# Generated by Django 3.2.9 on 2021-11-18 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='user',
            field=models.ManyToManyField(related_name='like_genres', to=settings.AUTH_USER_MODEL),
        ),
    ]
