# Generated by Django 3.2.9 on 2021-11-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_genre_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
