# Generated by Django 3.2.9 on 2021-11-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_review_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
    ]
